#!/bin/bash

pacman -S --needed git base-devel
git clone https://aur.archlinux.org/yay.git
cd yay
makepkg -si
cd .. && sudo rm -r yay

sudo pacman -S --noconfirm --needed - < pkglist.txt
sudo pacman -Rs picom
#for word in $(cat pkglist_aur.txt); do yay -S --needed $word || true; done
exec 9<pkglist_aur.txt
while read -u9 pkg; do yay -S --noconfirm --needed $pkg; done
chmod -R +x ./.scripts/
sed -i "s/salil/$USER/g" ./.scripts/* ./.config/bspwm/* ./.config/sxhkd/* ./.config/rofi/* ./.config/fish/*
cp -R ./.config ./.scripts ./.cache ./.local ~/
cd ~/.config/st
sudo make install
cd ~/autoricer
sudo pip3 install pywal
sudo pip install spotify-cli-linux
pip install dbus-python
cp -R wallpapers ~/Pictures/
chsh -s /usr/bin/fish
sudo pacman -Syu
